Menu:
  Home:
    url: /
    text: 主页
  Tag:
    url: /tags
    text: 标签
  Archive:
    url: /archives
    text: 归档
  About:
    url: /about
    text: 关于
# 图标放到source文件夹
Icon:
  # 此处放置网站图标
  Favicon: /images/favicon.ico
  # 此处放置收款码
  Payment: /images/alipay.png
# 是否开启侧边栏的小工具
Tool:
  enable: true
  app: /app.apk
Footer:
  # 统计工能是否开启
  counter: true
  # 统计功能服务器
  server: https://meethigher.top:9090/count/
  #网站开始运行的时间，格式"YYYY/MM/DD HH:mm:ss"，不填写，默认时间为2020年4月1日
Begin: "2019/09/15 19:57:09"
