Menu:
  Home:
    url: /
    text: 主页
  Tag:
    url: /tags
    text: 标签
  Archive:
    url: /archives
    text: 归档
Icon:
   Favicon: /images/favicon.ico
Aside:
  Avatar: /images/kitchen.jpg
  Author: 言成
  Description: 爱学习，爱运动，爱看妹子
  Github: https://github.com/meethigher
  Email: meethigher@qq.com
  Weixin: /images/weixin.png
Footer:
  counter: true
  #网站开始运行的时间，格式"YYYY/MM/DD HH:mm:ss"，不填写，默认时间为2020年4月1日
  begin: "2019/09/15 19:57:09"
