Menu:
  Home:
    url: /
    text: 主页
  Tag:
    url: /tags
    text: 标签
  Archive:
    url: /archives
    text: 归档
  About:
    url: /about
    text: 关于
Icon:
   Favicon: /images/favicon.ico
   ##此处放置收款码
   Payment: /images/alipay.png
Footer:
  counter: true
  #网站开始运行的时间，格式"YYYY/MM/DD HH:mm:ss"，不填写，默认时间为2020年4月1日
  begin: "2019/09/15 19:57:09"
